bug fixes and style changes
blue menus, blue settings, including state changes to show/hide the
menu window div, giving settings an actual overgrey, and spacing out
menu/settings buttons.
CHANGE: remove “exchange it with” action in favor of “give it to”,
FIX: empty icons were showing in combine menus
HACK for missing item return text — before/after actions are falling
into the scope of the event.
FIXED: error during exeunt:  -- ctrl.which is not a function
http://localhost:8080/demo/mapControl.js:170 -- regression due to prior
statemachine refactor
FIXED: give/show order in action list: added orderBy filter
FIXED: order of save games: added orderBy filter